version: "3.3"
services:
  omics:
    image: omics_r43:v2.0
    ports:
       - 6322:6322
    volumes:
       - /data1:/data1
    networks:
      meta_net:
        ipv4_address: 172.16.1.4
  web:
    image: smetabobank:v2.1
    ports:
       - 8085:8088
    volumes:
       - /metabobank_data:/metabobank_data
       - /data1:/data1
    environment:
       - TZ=Asia/Shanghai
    command: /start.sh
    networks:
      meta_net:
        ipv4_address: 172.16.1.2
  mongodb:
    image: mongod:v3.6
    ports:
       - 27027:27027
    environment:
       - TZ=Asia/Shanghai
    command: /mongodb/bin/mongod_client_free --config /mongodb/conf/mongodb.conf
    volumes:
       - /mongodb/conf:/mongodb/conf
       - /mongodb/dbs:/mongodb/dbs
       - /mongodb/logs:/mongodb/logs
    networks:
      meta_net:
        ipv4_address: 172.16.1.3 
networks:
  meta_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.1.0/24"
